"""
engine/output_generator.py — Assembles the three output artefacts from
an extracted bundle.

Given a completed output bundle (from profile.to_output_bundle()), produces:
    schema.sql  — CREATE TABLE DDL for this exam type
    data.json   — the full extracted bundle, ready for inspection or insert
    insert.py   — standalone Python script that inserts data.json into Postgres

OutputGenerator does not write files itself — it returns the content as
strings. The caller (pipeline or API endpoint) decides where to write them,
whether that is disk, Supabase storage, or an in-memory response.
"""

import json
from datetime import datetime, timezone


class OutputGenerator:

    def __init__(self, profile, bundle: dict):
        """
        profile — the ExamProfile instance that produced the bundle
        bundle  — the dict returned by profile.to_output_bundle()
        """
        self.profile = profile
        self.bundle  = bundle

    # ── Core generators ───────────────────────────────────────────────────────

    def generate_schema(self) -> str:
        """
        Return the SQL schema string for this exam type.
        Includes a header comment with generation metadata.
        """
        meta   = self.bundle.get("meta", {})
        header = (
            f"-- Generated by Exam PDF Extraction Engine\n"
            f"-- Exam type    : {meta.get('display_name', self.profile.display_name)}\n"
            f"-- Generated at : {meta.get('generated_at', datetime.now(timezone.utc).isoformat())}\n"
            f"-- Engine ver   : {meta.get('engine_version', '1.0')}\n"
            f"--\n"
            f"-- Run this once on your target database before executing insert.py\n"
            f"-- Safe to re-run — all statements use IF NOT EXISTS\n\n"
        )
        return header + self.profile.schema_sql()

    def generate_json(self, indent: int = 2) -> str:
        """
        Return the bundle as a formatted JSON string.
        This is the data.json artefact — the full extracted content
        in the standard envelope format.
        """
        return json.dumps(self.bundle, indent=indent, ensure_ascii=False)

    def generate_insert_script(self) -> str:
        """
        Return the insert.py script as a string.
        Delegates to the profile which knows its own table structure.
        """
        return self.profile.insert_script(self.bundle)

    # ── Convenience: generate all three at once ───────────────────────────────

    def generate_all(self) -> dict:
        """
        Generate all three artefacts in one call.

        Returns:
        {
            "schema.sql": "...",
            "data.json":  "...",
            "insert.py":  "...",
        }
        """
        return {
            "schema.sql": self.generate_schema(),
            "data.json":  self.generate_json(),
            "insert.py":  self.generate_insert_script(),
        }

    # ── Summary stats ─────────────────────────────────────────────────────────

    def summary(self) -> dict:
        """
        Return a lightweight summary of what was extracted.
        Used by the pipeline logger and API response.
        """
        paper     = self.bundle.get("paper", {})
        questions = self.bundle.get("questions", [])
        schemes   = self.bundle.get("schemes", [])

        q_ids = {q["simple_id"] for q in questions}
        s_ids = {s["simple_id"] for s in schemes}

        return {
            "exam_type":        self.profile.exam_type,
            "paper_code":       paper.get("paper_code"),
            "year":             paper.get("year"),
            "total_marks":      paper.get("total_marks"),
            "questions_count":  len(questions),
            "schemes_count":    len(schemes),
            "matched":          sorted(q_ids & s_ids),
            "unmatched_q":      sorted(q_ids - s_ids),
            "unmatched_s":      sorted(s_ids - q_ids),
            "has_all_schemes":  q_ids == s_ids if schemes else None,
        }